version: '3.8'

networks:
  default:
    name: ${COMPOSE_NETWORK_NAME}
    driver: bridge

services:
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: messenger_db
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ${COMPOSE_VOLUME_PREFIX}pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    name: ${COMPOSE_VOLUME_PREFIX}pg_data